### ISSUE TITLE
Comments on production branch - 2017.08.11

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/xmltoldmigration#13]
The migration is looking quite good. I noticed a few items and thought I'd put them in a single issue rather than raising a bunch of separate issues:

1. omit `:workLocationEndVolume` unless it differs from `:workLocationVolume`?

2. `:itemBDRCHoldingStatemeent` is misspelled

3. need `skos:prefLabel` for `:Work` from outline that only have title

4. do not migrate `p:event/@pid` simply add event as blank node

5. consider explicit `:workPartOf` instead of `:workHasPart` - individual nodes more nearly constant size; otoh, easier to navigate the ttl from the top w/ `:workHasPart`?

6. Standalone `:ItemPhysicalAsset` ttl do not use prefixes, but `:ItemImageAsset` do. For example, I00KG03673_002.

7. spot check of Corporations turned up:

```
     bdr:C2CN11015  a           :Corporation ;
         skos:altLabel          "myang stod khu le rgya yi rigs"@bo-x-ewts ;
         skos:prefLabel         "myang stod khu le'i rgya yi rigs rgyud"@bo-x-ewts , "myang stod khu le'i rgya rigs"@en ;
```

which is unfortunate since the English name is clearly just another ewts variant. There's probably nothing that can be done programmatically

8. spot check of Offices found R8LS13081 which needs to migrate type-less descriptions as  `skos:prefLabel` and `skos:altLabel`. In this case there is no identifying information in the rdf

9. G1KR1636 has a `:noteText` that is Tibetan unicode but tagged as English. Perhaps a later task can be to scan the data for such situations and adjust the tagging

10. `:WorkCreator` probably ought to be modeled like `:WorkTitle` and `:PersonName`?

**Comment by eroux** [comment]
I've fixed all the points except 7 and 10. I agree with you for point 10. For point 7 I can do some manipulations like checking if the converted Unicode string is valid classical tibetan. That will certainly make the conversion slower but it's not really difficult, tell me if you want me to give it a try. There are also some other annoying cases which could be taken care of, like the pubinfo fields that are often tagged wrongly as ewts, I can make a code path specifically for these fields where they are tagged as phonetics if they don't convert well to ewts...
