### ISSUE TITLE
Several Places have errors when transferring to fuseki

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/xmltoldmigration#2]
During couchdb to fuseki transfers of a very few Place documents, errors are thrown for content like in G1164:

    "plc" : "",

which seems to arise from:

    <g:gis>
        <g:id/>
        <g:coords/>
    </g:gis>`

The Places that seem to have problems are:

G1164
G1PD110071
G3997
G3CN1561
G3CN711

I haven't checked the others but they are likely similar to G1164.

**Comment by eroux** [comment]
Thanks, I suspected something like that but I'm glad you identified it! I'm currently adding more checks to the migration, I think there are still some similar errors here and there. I've started this morning but was busy the rest of the day, I should have something working nicely on monday
