### ISSUE TITLE
workLocationWork for outlines?

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/xmltoldmigration#20]
outlines are inconsistant in specifying the work location:

- [O01CT0042](https://www.tbrc.org/xmldoc?rid=O01CT0042) doesn't specify it
- [O00KG0561](https://www.tbrc.org/xmldoc?rid=O00KG0561) does
- [O1PD35544](https://www.tbrc.org/xmldoc?rid=O1PD35544) only specifies work (no page, volume, etc.)

the third case is obviously wrong and I'll fix it in the migration, but I think keeping the `workLocationWork` for an outline node is fairly redundant, and the info could be easly inferred (along with the `workLocationEndVolume` for instance). wdyt?

**Comment by xristy** [comment]
I think we should put Work, Volume, and Page consistently so that we don't have to make additional queries to get all the info needed to fetch pages. [O1PD35544](https://www.tbrc.org/xmldoc?rid=O1PD35544) needs to be reported to Karma so that it can be fixed. As it is, it would seem useless.
