### ISSUE TITLE
reducing image list length

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/xmltoldmigration#21]
I forgot to discuss about that yesterday so I'm opening an issue not to forget: I've [added](https://github.com/BuddhistDigitalResourceCenter/xmltoldmigration/commit/771cb730a7400fc706b812a394dde3c9cb32fb38) some simple code that changes the format of the image list in a quite safe way, basically replacing

```
41580001.tif|41580002.tif|41580003.tif|41580004.tif|41580005.tif|41580006.tif|41580007.tif|41580008.tif|41580009.tif|41580010.tif|41580011.tif|41580012.tif|41580013.tif|41580014.tif|41580015.tif|41580016.tif|41580017.tif|41580018.tif|41580019.tif|41580020.tif|41580021.tif|41580022.tif|41580023.tif|41580024.tif|41580025.tif|41580026.tif|41580027.tif|41580028.tif|41580029.tif|41580030.tif|41580031.tif|41580032.tif|41580033.tif|41580034.tif|41580035.tif|41580036.tif|41580037.tif|41580038.tif|41580039.tif|41580040.tif|41580041.tif|41580042.tif|41580043.tif|41580044.tif|41580045.tif|41580046.tif|41580047.tif|41580048.tif|41580049.tif|41580050.tif|41580051.tif|41580052.tif|41580053.tif|41580054.tif|41580055.tif|41580056.tif|41580057.tif|41580058.tif|41580059.tif|41580060.tif|41580061.tif|41580062.tif|41580063.tif|41580064.tif|41580065.tif|41580066.tif|41580067.tif|41580068.tif|41580069.tif|41580070.tif|41580071.tif|41580072.tif|41580073.tif|41580074.tif|41580075.tif|41580076.tif|41580077.tif|41580078.tif|41580079.tif|41580080.tif|41580081.tif
```

with

```
41580001.tif--41580081.tif
```

(of course handling all sorts of edge cases, we can review the code if you want). I was itching to do that for quite some time as it seems quite a waste of space... And indeed, the size of them items directory (file size) got divided by 3.54... I think it's really worth it especially since this is an internal string for machines, not for users... wdyt?

**Comment by xristy** [comment]
Doh! Two heads are better than one.

I can offer:

    41580001.tif:81

even shorter, etc

**Comment by eroux** [comment]
Great! I like your idea, I'll implement it
