### ISSUE TITLE
capturing etext reference

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/xmltoldmigration#22]
Looking at [O4JW333](https://www.tbrc.org/xmldoc?rid=O4JW333) I realize there are two description types we do not capture:

- `icon` (although I'm not sure it's relevant)
- `text`, which contains a reference to an etext:

```xml
<outline:description type="text">UT22084-051-004</outline:description>
```

I'm not really sure how to capture that... ?

**Comment by xristy** [comment]
`O5JW1143` also has text refs.
