### ISSUE TITLE
itemPhysicalAssetForWork etc.

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/xmltoldmigration#25]
@xristy : while I believe it's useful to have

```ttl
bdr:W123 :workHasItemPhysicalAsset bdr:I123_P001 
```

when we are looking specifically for physical assets and not any kind of item, I'm not sure what benefit

```ttl
bdr:I123_P001 :itemPhysicalAssetForWork bdr:I123_P001
```

brings (apart from the satisfaction to have a symetric property to `:workHasItemPhysicalAsset`). Let me try to explain why:

Even though we will be using a triple store for the main front end, I think the separation into several different files is still largely relevant because it's how our reference data is organized. And these different files may be used as separate entities by some parts of our technological stack (the blmp, the app? a lot of curation code, etc.).

In this perspective, when some code reads a work file, it may want to ask "does this work have etexts?" without opening all the related item files (which is exactly the case that led me to propose the various `:workHasItem` subproperties).

On the other hand, when reading an item document, provided the resource has an `rdf:type`, I'm not sure what benefit there is in having `:itemPhysicalAssetForWork` instead of `:itemForWork`? But in a SPARQL query perspective, I agree it can make sense. 

Lemma: the `:itemForWork` properties can be inferred per-document (without looking at other documents), with simple Jena rules like:

```
[ifwpa: (?a rdf:type :itemPhysicalAsset), (?a :itemForWork ?b) -> (?a :itemPhysicalAssetForWork ?b)]
```

So my proposal would be to keep `:itemForWork` for the `.ttl` files in the git repo for the sake of simplicity, and to infer the `:itemForWork` subproperties in the reasoning pass.

wdyt?

**Comment by xristy** [comment]
Great!
