### ISSUE TITLE
Volumes documents are badly formed

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/xmltoldmigration#3]
During couchdb to fuseki transfers of Volumes documents, each document is throwing errors:

> Processing: vol:V00CHZ0103340 throws org.apache.jena.shared.BadURIException: Only well-formed absolute URIrefs can be included in RDF/XML output: <http://purl.bdrc.io/ontology/volumes#http://purl.bdrc.io/ontology/volumes#I1CZ30> Code: 0/ILLEGAL_CHARACTER in FRAGMENT: The character violates the grammar rules for URIs/IRIs.

This coming from:

    "vol:hasVolume" : [ {
      "@id" : "vol:http://purl.bdrc.io/ontology/volumes#I1CZ30",
      "@type" : "vol:Volume",
      "desc:noType" : {
        "@language" : "en",
        "@value" : "Volume 1 of gsung thor bu/ bsod nams lhun grub"
      },
      "vol:imageList" : "I1CZ300001.tif|I1CZ300002.tif|I1CZ300003.tif|. . . ",
      "vol:pages_tbrcintro" : {
        "@type" : "xsd:nonNegativeInteger",
        "@value" : "2"
      },
      "vol:pages_total" : {
        "@type" : "xsd:nonNegativeInteger",
        "@value" : "446"
      }
    }

We need a different `@id` for the individual volume

**Comment by eroux** [comment]
Thanks! The fact that these errors only show up during xml serialization (and not json one) is quite annoying... maybe I should also perform an xml serialization as a sanity check during the migration... I'll try that

**Comment by xristy** [comment]
It is sufficient to use a convention like:

    "@id" : vol: V00CHZ0103340_I1CZ30

i.e., just append the ImageGroup id to the Volumes id. This is the naming convention that we use in archive.

ALSO, the `vol:number` property should be present on each vol:Volume like:

    "vol:number" : 1

**Comment by eroux** [comment]
should be fixed
