### ISSUE TITLE
missing :PersonOtherTitle needs change mapping

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/xmltoldmigration#34]
Nicolas noticed that XML person name type `title` was mapped to `:PersonTitle`; however, that class does not appear in the ontology.

I noticed that there was `:PersonOtherName` to which `otherName` was mapped and so have added `:PersonOtherTitle` as the migration target for `title` since `title` appears to be an otherwise unspecified type of title, i.e., an other title.

So xmltoldmigration needs to be changed accordingly.

**Comment by eroux** [comment]
I suppose that due to `PersonTitle` having appeared in the ontology ([here](https://github.com/BuddhistDigitalResourceCenter/owl-schema/commit/9ce959f3eb45f3120c3e593b4d2b4eae98dd2f61)) this issue can be closed?

**Comment by xristy** [comment]
Yes indeed. I had added :PersonOtherTitle and then looked at changing xmltoldmigration but realized that it would be simpler to just add :PersonTitle and then I forgot to link the commit to this issue
