### ISSUE TITLE
understand lineageAlternative

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/xmltoldmigration#47]
`:lineageAlternative` is used (and misspelled) in the migration but is absent from the ontology...

It is used for instance in L8LS15118 ([xml](https://www.tbrc.org/xmldoc?rid=L8LS15118), [ttl](http://purl.bdrc.io/resource/L8LS15118.ttl))... I'm not really sure if it's missing from the ontology or if I should replace it with another property... @xristy what do you think?

**Comment by xristy** [comment]
Perhaps Lobasang needs to be queried as to why that construct was used as it was.

According to the lineage.xsd, the alternative is included in a doc that has a main lineage, not as a standalone thing. In any event it would seem that it likely should be included in the ontology - I will take a look. Here's the xsd fragment:

```xml
   <xsd:complexType name="Alternative">
        <xsd:annotation>
            <xsd:documentation>An Alternative is used to express a variant of the main lineage inline in the same Lineage document rather than creating separate documents for each lineage variation. It is modeled on the conventions used in gsan yig for this purpose. So an Alternative will typically have three or more holders: 1) the start holder that mentions a holder in the containing Lineage that is the start point of the variation; 2) then one or more holders that represent the variation; and
                3) then a final holder that mentions a holder in the containing Lineage that is the end point of the variation. The start holder is marked by including a downTo element and the end holder is marked with a downFrom element. If the downTo holder is not present then the variation is a variation on the intial sequence of the lineage. If the downFrom is not present then the variation is a the end of the lineage. Generally the Alternatives should appear at the end of the main sequence
                of holders and there may be as many Alternatives as needed to express the variations in the gsan yig / thob yig.</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="holder" type="lin:Holder" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

**Comment by xristy** [comment]
the intent of the lineage:alternative is defeated the way it's been used since it doesn't indicate what it's an alternative of.

The original model was developed for Ralph Kramers' lineage data and there are no occurrences of lineage:alternative in his data.

Lobsang seems to have used it 116 out of 1199 lineage docs that he added so he apparently had something in mind.

If he doesn't have a good answer I suggest we delete the lineage alternative and treat it as a main lineage otherwise how do figure out what it is an alternative of?

**Comment by eroux** [comment]
@lobsangshastri would you have time to explain what the "alternative" in L8LS15118 means?

**Comment by xristy** [comment]
I also note that at least one of the lineage docs, L8LS15732, has a bunch of empty holders as though it either isn't completed or a bunch of unneeded holders were added and not removed after completing the lineage

**Comment by xristy** [comment]
There are a series of lineage docs: [L2RKL871](https://www.tbrc.org/xmldoc?rid=L2RKL871) - [L2RKL8728](https://www.tbrc.org/xmldoc?rid=L2RKL8728) which are alternatives.These docs use lineage: lineageRef to refer to another lineage and otherwise use lineage:not to mention the original lineage id that Ralph used in his data

**Comment by xristy** [comment]
did Lobsang answer? Or are you asking me? If it's up to me I'd delete the lineage:alternative and simply write the lineage like the others. If there's info about what it is an alternative to then that could be added via lineage:lineageRef

**Comment by eroux** [comment]
No answer, @karmagongde what do you think? If there's no answer I'll proceed as you said

**Comment by karmagongde** [comment]
@eroux The alternative linage means If one Lama has received a transmission of a particular texts/teaching from 2 or more teachers is called alternative linage.

**Comment by xristy** [comment]
@karmagongde the `lineage:lineageAlternative` was not used in the original Ralph Kramer lineage docs. The way that it has been used in the 116 cases of `L8LS...` is not in accord with the model. The original intent was that an alternative would be included in the lineage document that the alternative was an alternative to. 

That was deemed to be too unwieldy and alternatives were separate docs as in the cases of [L2RKL871](https://www.tbrc.org/xmldoc?rid=L2RKL871) - [L2RKL8728](https://www.tbrc.org/xmldoc?rid=L2RKL8728) where `lineage:note`s and `lineage:lineageRef`s clarify the relationships. 

The usage of`lineage:lineageAlternative` in the current cases does not include a `lineage:lineageRef` or a `lineage:note` so there is no way to know what it is an alternative to.

It will be sufficient to migrate these 116 case as simple lineage docs with `lineage:downFrom`s and `lineage:downTo`s.

We will simply retire the `lineage:lineageAlternative` as should have been done some years ago.
