### ISSUE TITLE
property indicating "root" part

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/xmltoldmigration#48]
We currently infer the root part of a work (ex: [W22084_1088](http://library.bdrc.io/show/bdr:W22084_1088):
- `:workPartOf` [W22084_S0013](http://library.bdrc.io/show/bdr:W22084_S0013)
- has root part [W22084](http://library.bdrc.io/show/bdr:W22084)

We currently use `tmp:workRootWork`, but then we have the problem of defining a `skos:prefLabel`, etc. for this new property...

Maybe `:workPartOfRoot`?

**Comment by xristy** [comment]
resolved by adding :workHasRoot
