### ISSUE TITLE
types for some blank nodes

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/xmltoldmigration#6]
Some blank nodes (for notes and log entries) have type in the Google Drive document, if we remove the type from some blank nodes (names, titles, etc.) maybe we can remove the type for these too? We can easily add it back in the transfer to fuseki if it proves helpful. Wdyt?

**Comment by xristy** [comment]
No need to add `rdf:type` statements. I put them in _A Buddhist Digital Ontology_ for the benefit of the reader to indicate what the blank nodes are. As long as we have an understanding of how and where the validation of the contents of the blank nodes is done then adding the type assertion explicitly is something that can be be done via _inference_ based on the range defns of properties.
