### ISSUE TITLE
Outlines may have malformed descriptions

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/xmltoldmigration#7]
In several outlines the <o:description type="..."/> is represented in the content of the element instead of the @type, for example in O4JW333:

    <outline:description type="location">vol:1,ff.1r-311r(pp.1-621)</outline:description>
    <outline:description type="authorship">
    t. Sarvajñādeva (k); Vidyākaraprabha; Dharmākara (ka0; Dpal gyi lhun po; r. Vidyākaraprabha; Dpal brtsegs
    </outline:description>
    <outline:description>sde dge number 1</outline:description>
    <outline:description>stog number 1</outline:description>
    <outline:description>snar thang number 1</outline:description>
    <outline:description>lha sa number 1</outline:description>
    <outline:description>urga number 1</outline:description>
    <outline:description type="toh">1</outline:description>
    <outline:description type="sde dge number">1</outline:description>

this also illustrates duplication of the `sde dge number`.

**Comment by eroux** [comment]
Only 3 outlines seem to suffer from this problem, here are the fixed versions of these: 
[fixed-outlines.zip](https://github.com/BuddhistDigitalResourceCenter/xmltoldmigration/files/1266345/fixed-outlines.zip) can you quickly check them before I (or you) upload them to exist?

I figured it was easier to fix them directly than having tedious code to handle all the various cases like the spelling mistakes and cases where the description has a type like

```xml
<outline:description type="location">lha sa number 1</outline:description>
```

Note that I did not fix puzzling things like

```
<outline:description>snar thang number</outline:description>
```

(with no number), that's garbage data, but well, at least the interesting data will get transferred correctly...

**Comment by xristy** [comment]
Excellent! I'll upload these three. Thanks so much.

**Comment by xristy** [comment]
Corrections uploaded

**Comment by xristy** [comment]
`O5JW1143` also has malformed descriptions - it was a clone of `O4JW333`

**Comment by eroux** [comment]
[O5JW1143.xml.zip](https://github.com/BuddhistDigitalResourceCenter/xmltoldmigration/files/1267523/O5JW1143.xml.zip)
 here's the fixed version

**Comment by eroux** [comment]
A few others I just spotted: 
- [O2DB75712](https://www.tbrc.org/xmldoc?rid=O2DB75712) (ex: O2DB757121KG72517)
- [O00CR0008](https://www.tbrc.org/xmldoc?rid=O00CR0008) (ex: O00CR00084CZ281547)
- [O1PD181215](https://www.tbrc.org/xmldoc?rid=O1PD181215) (ex: O1PD1812154CZ133521)

**Comment by eroux** [comment]
The fixed outlines, can you upload them?

[fixed-outlines.zip](https://github.com/BuddhistDigitalResourceCenter/xmltoldmigration/files/1299073/fixed-outlines.zip)

**Comment by xristy** [comment]
I've uploaded these. 

I noticed that in a number of cases there were sde dge elements but no numbers which I assume will simply be filtered out via xml2ld

I also noted some section names in O1PD181215 that have some sort of invalid character next to a chinese character

**Comment by eroux** [comment]
Thanks for the upload! For the ignore:

```xml
<description type="sde dge number"></description>
```

is ignored, but

```xml
<description>sde dge number</description>
```

is not (hence part of the changes I made to these outlines)... I didn't really look for invalid characters, do you have a node ID in which it appears?

**Comment by xristy** [comment]
O1PD1812154CZ135987, O1PD1812154CZ136047, O1PD1812154CZ136352, etc The section names directly under the `skabs gsum pa/ rgyu mtshan nyid theg pa'i skor/ (ka-go)` section

**Comment by eroux** [comment]
indeed, it's also an `u+fffd` as in the other encoding problems...
